		<?php 
            $mn= Mage::app()->getRequest()->getParam("module_name"); 
            echo $mn;
        ?>
        <div>
        	<h4><?php echo $this->__('Edit Row'); ?></h4>
            <form id="myform" action="<?php echo $this->addFormHandler(); ?>" method="POST">
                <label>Title:</label><br><input type="text" name="title" id= "title" placeholder="Title" /><br/>
                <label>Content:</label><br><textarea type="text" name="content" id= "content" placeholder="Content" ></textarea><br/>
                <label>Status:</label><br>
                <select name="status" id= "status">
		            <option value="1" >Enabled</option>
		            <option value="2" >Disabled</option>
		        </select><br/><br>
                <input type="submit" name="sub" id="sub" value="Submit" />
            </form>
        </div>


<?php
//$news = Mage::getModel('test/test');
//if(isset($_POST["sub"])){
    //$title = Mage::app()->getRequest()->getParam("title");
    //echo $title;
	/*$news->setData($row);
    try{
                   $news->save();
                   echo "Data inserted successfully";
                         
        }
               catch(Exception $e){
                   echo $e->getMessage();
        }*/
//}
?>
