		<?php 
            $mn= Mage::app()->getRequest()->getParam("module_name"); 
            echo $mn;
        ?>
        <div>
        	<h4><?php echo $this->__('Edit Row'); ?></h4>
            <form id="myform" action="" method="POST">
                <label>Title:</label><br><input type="text" name="title" id= "title" placeholder="Title" /><br/>
                <label>Content:</label><br><textarea type="text" name="content" id= "content" placeholder="Content" ></textarea><br/>
                <label>Status:</label><br>
                <select name="status" id= "status">
		            <option value="1" >Enabled</option>
		            <option value="2" >Disabled</option>
		        </select><br/><br>
                <input type="submit" name="sub" id="sub" value="Submit" />
            </form>
        </div>


<?php
$sub = Mage::app()->getRequest()->getParam("sub");
if(isset($sub)){
    $module_name = Mage::app()->getRequest()->getParam("module_name");
    $post = Mage::app()->getRequest()->getParams();
    $this->addFormHandler();
    //Mage::getUrl('test/index/add', array('id'=>1));//'module_name'=>$module_name, 'title' => $title, 'content' => $content, 'status' => $status));
}
?>
